apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      initContainers:
        - name: wait-redis
          image: redis:7-alpine
          envFrom:
            - configMapRef:
                name: shared
          command:
          - sh
          - -ec
          - |
            until (redis-cli -u $REDIS_URL ping); do
              sleep 1
            done
      containers:
      - name: app
        image: {{ .Values.werf.image.web }}
        command: {{ .Values.command }}
        {{ if .Values.port }}
        ports:
        - containerPort: {{ .Values.port }}
        {{ end }}
        envFrom:
        - configMapRef:
            name: shared
        resources:
          {{- toYaml .Values.resources | nindent 10 }}